import { NextResponse } from 'next/server'
import type { Project } from '@/types'

const projects: Project[] = [
  {
    id: 1,
    name: 'PT Dea Trans Solusindo — Company Website',
    description: 'Full-stack company website for a freight forwarding company with admin dashboard, shipment tracking, and customer portal.',
    techStack: ['Next.js', 'React', 'MongoDB', 'Tailwind CSS', 'Node.js'],
    category: 'Web Development',
    status: 'Completed',
    year: 2025,
  },
  {
    id: 2,
    name: 'AI Customer Service Chatbot',
    description: 'Intelligent chatbot powered by Claude API with RAG pipeline for answering freight forwarding inquiries automatically.',
    techStack: ['Claude API', 'Next.js', 'Vercel AI SDK', 'PostgreSQL', 'Docker'],
    category: 'AI Integration',
    status: 'In Progress',
    year: 2025,
  },
  {
    id: 3,
    name: 'Social Media Growth Campaign — DeaTrans',
    description: 'Strategic Instagram & TikTok organic growth campaign achieving 360% reach increase in 6 months.',
    techStack: ['Meta Business Suite', 'Instagram', 'TikTok', 'Canva', 'CapCut'],
    category: 'Digital Marketing',
    status: 'Completed',
    year: 2024,
  },
  {
    id: 4,
    name: 'HRGA Management System',
    description: 'Internal HR & General Affairs management system for employee data, attendance, and payroll processing.',
    techStack: ['Next.js', 'PostgreSQL', 'Prisma', 'TypeScript', 'Tailwind CSS'],
    category: 'HR System',
    status: 'Completed',
    year: 2024,
  },
  {
    id: 5,
    name: 'Office Network Infrastructure',
    description: 'Complete IT infrastructure setup including network topology, VPS deployment, CCTV system, and Linux server configuration.',
    techStack: ['Linux', 'Nginx', 'Docker', 'MikroTik', 'CCTV DVR'],
    category: 'IT Support',
    status: 'Completed',
    year: 2023,
  },
  {
    id: 6,
    name: 'Meta Ads Performance Dashboard',
    description: 'Custom analytics dashboard for tracking Meta Ads performance, ROAS, and campaign metrics in real-time.',
    techStack: ['React', 'Meta Marketing API', 'Chart.js', 'Node.js', 'MongoDB'],
    category: 'Digital Marketing',
    status: 'Completed',
    year: 2024,
  },
  {
    id: 7,
    name: 'RAG-Powered Document Assistant',
    description: 'AI assistant with Retrieval Augmented Generation for querying company documents, SOPs, and compliance materials.',
    techStack: ['Claude API', 'LangChain', 'Pinecone', 'Next.js', 'TypeScript'],
    category: 'AI Integration',
    status: 'In Progress',
    year: 2025,
  },
  {
    id: 8,
    name: 'E-Commerce Admin Panel',
    description: 'Admin dashboard with product management, order tracking, inventory system, and customer CRM integration.',
    techStack: ['Next.js', 'React', 'MySQL', 'Prisma', 'Shadcn UI'],
    category: 'Web Development',
    status: 'Completed',
    year: 2023,
  },
  {
    id: 9,
    name: 'Employee Attendance & Payroll',
    description: 'Automated attendance tracking system with biometric integration and payroll calculation module.',
    techStack: ['Go', 'PostgreSQL', 'React', 'Docker', 'REST API'],
    category: 'HR System',
    status: 'Completed',
    year: 2022,
  },
  {
    id: 10,
    name: 'TikTok Content Strategy & Production',
    description: 'Full content strategy, filming, editing, and publishing workflow for TikTok brand presence growth.',
    techStack: ['TikTok Studio', 'CapCut', 'Adobe Premiere', 'Canva'],
    category: 'Digital Marketing',
    status: 'Completed',
    year: 2024,
  },
  {
    id: 11,
    name: 'VPS Linux Server Setup & Security Hardening',
    description: 'Production VPS configuration with Nginx, SSL, firewall rules, automated backups, and monitoring.',
    techStack: ['Ubuntu Server', 'Nginx', 'Certbot', 'UFW', 'Fail2ban'],
    category: 'IT Support',
    status: 'Completed',
    year: 2023,
  },
  {
    id: 12,
    name: 'Portfolio Website (This Site)',
    description: 'Personal portfolio built with Next.js 16, TypeScript, TanStack Query & Table, Tailwind CSS, and dark/light mode.',
    techStack: ['Next.js', 'TypeScript', 'TanStack', 'Tailwind CSS', 'Vercel'],
    category: 'Web Development',
    status: 'Completed',
    year: 2025,
  },
]

export async function GET() {
  return NextResponse.json({ data: projects, total: projects.length })
}
